Added setting to allow filtering of user registrations in ldap storage provider
added basic tests to the feature

hide filter button if sync is off

better messages in admin

Allow filtering of user regsitrations within ldap store

Added setting to allow filtering of user registrations in ldap storage provider

ldap - filter registrations based on username

added basic tests to the feature

KEYCLOAK-17935 SAML Client - Validate InResponseTo attribute

KEYCLOAK-18091 Fail session loading when interrupted

[KEYCLOAK-18473] Add max length to password policy

[KEYCLOAK-17443] Username and email form fields kept in registration
form when duplicate

KEYCLOAK-17446 - Prefill username in "Forgot Your Password" form if
called from Login form

[KEYCLOAK-18447] Dynamically select attributes based on requested scopes

[KEYCLOAK-14046] Allow finegrain group admins to create users in console

- enable "Create" button and "Save" button in Admin Console Users views (list
and details)

The flag used to enable those button is computed as follow, since there's no computed flag
from backend on "admin user has fine grain admin permission on at least 1 group" :
  == (existing condition) || (feature "finegrain admin" is enabled && access.queryUsers)

If the admin user hasn't the correct permission on the right groups for the new user he's
trying to create, backend will forbid the creation by returning a 403

This change is following PR #7035, which added the Groups field in the User creation form

KEYCLOAK-12500 Avoid NPE when parsing JWKS and keys without the use parameter

[KEYCLOAK-16455][Adapter - JavaScript] Propagate 3rd party cookies check
errors outside of JS adapter

KEYCLOAK-18450 Add basic tests for the Identity Provider Redirector Default IdP feature

KEYCLOAK-18534 Fix js tests timeout failure

KEYCLOAK-18423 - Support a user-friendly name property for user profile
attributes

KEYCLOAK-18503 Regex Policy for authorization service

[KEYCLOAK-18426] - Support required by role and scopes in Admin UI

KEYCLOAK-15371 Dont show backchannel logout options for bearer only clients in admin ui

[KEYCLOAK-18428] - dynamic registration form

[KEYCLOAK-18427] - Allowing switching to declarative provider

KEYCLOAK-17936 FAPI-CIBA : support Signed Authentication Request

Co-authored-by: Pritish Joshi <pritish@banfico.com>
Co-authored-by: mposolda <mposolda@gmail.com>

KEYCLOAK-18505 ConfigMigrationTest failures

KEYCLOAK-18560 NoClassDefFoundError: Could not initialize class org.keycloak.util.JWKSUtils

KEYCLOAK-18390 GroupProvider search implementation of JPA and Map delivers different results

KEYCLOAK-18391 CIBATest failures

KEYCLOAK-18315 SAML Client - Add parameter to request specific AttributeConsumingServiceIndex

KEYCLOAK-18583 Remove OIDCWellKnownProvider.isAsymmetricAlgorithm

KEYCLOAK-18554 Make ErrorHandler to log all errors for debugging purposes

KEYCLOAK-17781 Make exists and notExists collection aware

KEYCLOAK-18592 - put attribute validators configuration into freemarker
template for user profile pages

KEYCLOAK-18603 Remove duplicated statement

This is super minor but saw this while reading this file.

KEYCLOAK-18589 map-storage profile for KeycloakServer

KEYCLOAK-18502 - Support for additional parameters from the backchannel authentication request and backchannel authentication callback.

KEYCLOAK-18147 Fix CodeQL failures

KEYCLOAK-18414 Remove unnecessary id parameter from create operation

KEYCLOAK-18414 Remove unnecessary id parameter from update operation

KEYCLOAK-18194 fix migration of default role when realm id contains apostrophe

KEYCLOAK-15572 make attributes multi-valued for map storage entities

KEYCLOAK-18542 - User Profile Admin UI - hide unused configurations for
username and email attributes

[KEYCLOAK-18425] - Allow mapping user profile attributes

KEYCLOAK-18635 Move classes specific to ConcurrentHashMap to chm package

[KEYCLOAK-18626] - Avoid changing username when registration as email is enabled

[KEYCLOAK-18424] GUI order for user profile attributes

[KEYCLOAK-18429] Support a dynamic update profile form

KEYCLOAK-18452 FAPI JARM: JWT Secured Authorization Response Mode for OAuth 2.0

KEYCLOAK-18353 Implement Pushed Authorization Request inside the Keycloak

Co-authored-by: Takashi Norimatsu <takashi.norimatsu.ws@hitachi.com>
Co-authored-by: mposolda <mposolda@gmail.com>

KEYCLOAK-17937 Client Policy - Endpoint : support CIBA Backchannel Authentication Endpoint

* Add sid claim to ID Token
* deprecate session state parameter in ID Token
* remove charset=UTF-8 from backchannel logout post request Content-Type header

KEYCLOAK-18639 Token Exchange SPI Milestone 1

hide filter button if sync is off

ldap - filter registrations based on username

better messages in admin

ldap - filter registrations based on username